### ISSUE TITLE
Codecov uploader uploads an empty cov report 

### ISSUE THREAD

**Issue by ArttuLe** [Origami-TinyML/tflm_hello_world#33] opened 2023-01-24 06:23 UTC
#32 
CI pipeline with code coverage reporting is working but codecov uploader uploads an empty coverage report. Bug in codecov's side?

**Comment by ArttuLe** [comment] 2023-01-24 06:24
https://about.codecov.io/blog/how-to-set-up-codecov-with-c-and-github-actions/

**Comment by doyu** [comment] 2023-01-24 09:54
html would be ok. You can use love, then

**Comment by FexbYk23** [comment] 2023-01-24 10:40
The cause of this seemed to be that codecov requires access to the source code to show the coverage reports. This could be fixed by including the tflite-micro source code in this repo instead of cloning it in the docker container.

**Comment by doyu** [comment] 2023-01-24 12:00
codecov may be overkilling in this case? lcov may be just ok for us?

@FexbYk23 what do you think?

**Comment by doyu** [comment] 2023-01-24 14:03
@ArttuLe managed to make all work with codecov. Let's stick to the original plan, then.

**Comment by doyu** [comment] 2023-01-24 14:04
Closing. Please continue this in the original issue (i.e. BI). Thanks!

**Closed by doyu** 2023-01-24 14:04 UTC
